[package]
name = "prayer-times-app"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slint = "1.0.0"
chrono = "0.4"

[build-dependencies]
slint-build = "1.0.0"